// Fictional Slovak and Czech names, with the feminine surname forms, and places for addresses. None of
// the generated names may contain "Novák" or "Horváth": the demo customer and a scripted customer own them,
// and tests look them up by name.

export const MALE_FIRST_NAMES = [
  'Adam',
  'Andrej',
  'Branislav',
  'Daniel',
  'Dávid',
  'Dominik',
  'Filip',
  'Igor',
  'Jakub',
  'Ján',
  'Jozef',
  'Juraj',
  'Kamil',
  'Lukáš',
  'Marek',
  'Matej',
  'Michal',
  'Milan',
  'Miroslav',
  'Oliver',
  'Pavol',
  'Patrik',
  'Radoslav',
  'Richard',
  'Róbert',
  'Roman',
  'Samuel',
  'Stanislav',
  'Šimon',
  'Tomáš',
  'Viktor',
  'Vladimír',
];

export const FEMALE_FIRST_NAMES = [
  'Adriana',
  'Alena',
  'Andrea',
  'Barbora',
  'Diana',
  'Dominika',
  'Eliška',
  'Gabriela',
  'Ivana',
  'Jana',
  'Kristína',
  'Laura',
  'Lenka',
  'Lucia',
  'Mária',
  'Martina',
  'Michaela',
  'Monika',
  'Natália',
  'Nikola',
  'Petra',
  'Renáta',
  'Simona',
  'Soňa',
  'Tamara',
  'Terézia',
  'Veronika',
  'Viktória',
  'Zdenka',
  'Zuzana',
];

/** Masculine form and feminine form. */
export const SURNAMES: [string, string][] = [
  ['Bartoš', 'Bartošová'],
  ['Beňo', 'Beňová'],
  ['Blaško', 'Blašková'],
  ['Čech', 'Čechová'],
  ['Dobrovský', 'Dobrovská'],
  ['Ďurica', 'Ďuricová'],
  ['Fabian', 'Fabianová'],
  ['Gajdoš', 'Gajdošová'],
  ['Hanák', 'Hanáková'],
  ['Hrubý', 'Hrubá'],
  ['Chovanec', 'Chovancová'],
  ['Jurčík', 'Jurčíková'],
  ['Kanás', 'Kanásová'],
  ['Klimko', 'Klimková'],
  ['Kolesár', 'Kolesárová'],
  ['Kováč', 'Kováčová'],
  ['Krajčí', 'Krajčí'],
  ['Kubala', 'Kubalová'],
  ['Lacko', 'Lacková'],
  ['Lukáč', 'Lukáčová'],
  ['Majerník', 'Majerníková'],
  ['Marko', 'Marková'],
  ['Mikuš', 'Mikušová'],
  ['Molnár', 'Molnárová'],
  ['Nagy', 'Nagyová'],
  ['Oravec', 'Oravcová'],
  ['Pavlík', 'Pavlíková'],
  ['Polák', 'Poláková'],
  ['Rusnák', 'Rusnáková'],
  ['Sedlák', 'Sedláková'],
  ['Straka', 'Straková'],
  ['Šebo', 'Šebová'],
  ['Švec', 'Švecová'],
  ['Tkáč', 'Tkáčová'],
  ['Urban', 'Urbanová'],
  ['Vlček', 'Vlčková'],
  ['Zelenák', 'Zelenáková'],
  ['Žilinský', 'Žilinská'],
];

export const PLACES = [
  { city: 'Bratislava', zipCode: '811 01', country: 'SK' },
  { city: 'Košice', zipCode: '040 01', country: 'SK' },
  { city: 'Žilina', zipCode: '010 01', country: 'SK' },
  { city: 'Banská Bystrica', zipCode: '974 01', country: 'SK' },
  { city: 'Poprad', zipCode: '058 01', country: 'SK' },
  { city: 'Trnava', zipCode: '917 01', country: 'SK' },
  { city: 'Nitra', zipCode: '949 01', country: 'SK' },
  { city: 'Prešov', zipCode: '080 01', country: 'SK' },
  { city: 'Martin', zipCode: '036 01', country: 'SK' },
  { city: 'Praha', zipCode: '120 00', country: 'CZ' },
  { city: 'Brno', zipCode: '602 00', country: 'CZ' },
  { city: 'Ostrava', zipCode: '702 00', country: 'CZ' },
  { city: 'Kraków', zipCode: '31-042', country: 'PL' },
  { city: 'Budapest', zipCode: '1062', country: 'HU' },
];

export const STREETS = [
  'Hlavná',
  'Štefánikova',
  'Námestie SNP',
  'Hviezdoslavova',
  'Záhradnícka',
  'Mlynská',
  'Kollárova',
  'Nádražná',
  'Školská',
  'Lipová',
  'Jarná',
  'Kvetná',
  'Horná',
  'Dolná',
  'Sadová',
  'Partizánska',
];

export const COMPANIES = [
  'Tatra Outdoor a.s.',
  'Horizont Consulting s.r.o.',
  'Alpina Tech s.r.o.',
  'Liptov Build s.r.o.',
  'Nordic Data s.r.o.',
  'Snowline Media s.r.o.',
];

export const RENTAL_NOTES = [
  'Quick pickup, the skis were waxed and ready.',
  'Friendly staff who helped me pick the right length.',
  'Had to wait a while at the counter on Saturday morning.',
  'Easy return, no questions asked.',
  'Great advice on bindings for my kids.',
  'The store was busy, but they kept the line moving.',
];

export const MODEL_COMMENTS = [
  'Grippy on hard snow and very stable at speed.',
  'Forgiving and easy to turn, great for learning.',
  'Floats nicely in fresh snow, a bit heavy on the lift.',
  'Playful in the park, holds an edge better than expected.',
  'Too stiff for my level, would pick something softer next time.',
  'Light and lively, perfect for a full day on piste.',
];

export const BOOKING_NOTES = [
  'We arrive around 10:00.',
  'Could you set the bindings for a beginner?',
  'I may be a bit late on the first day, around noon.',
  'Two of us are sharing the booking, please keep the skis together.',
  'First time skiing, any advice on length is welcome.',
];
